### ISSUE TITLE
Freezing: use forbiddenfruit for patching "now"?

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.testing#22]
The current implementation of `freeze` is quite heavy since we are replacing the `datetime` module and class in order to replace the `now` method.
This has side-effects such as wrong `isinstance` check results or pickling errors.

We could use https://github.com/clarete/forbiddenfruit for replacing `now`, so that we only replace the method and keep the class.
This would make a lot quite simpler.

**Comment by jone** [comment]
```python
projects/packages/ftw.testing[jone-forbiddenfruit*]% ./bin/zopepy                                                                                                                                 jone4tw.local

>>> from forbiddenfruit import curse
>>> import time
>>> time.time
<built-in function time>
>>> curse(time, 'time', lambda: 4)
zsh: segmentation fault  ./bin/zopepy
```

@lukasgraf :disappointed: any idea?

**Comment by lukasgraf** [comment]
@jone ouch ;) Looks like this is the same behavior as described in https://github.com/clarete/forbiddenfruit/issues/6

But as stated in that issue:

> saying that modules are not welcome would be enough, since you can still patch them without cursing them.

There shouldn't be a need to use `forbiddenfruit` to patch `time.time` - classic monkey patching (including hunting down references) as done by labix mocker should work, don't you think?

**Comment by jone** [comment]
Indeed.
