### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.testing#41]
We probably should adapt the Readme so that we import `TestCase` from `unittest2` instead of `unittest` here from https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html.

**Comment by jone** [comment]
@busykoala Did you paste the wrong link? I don't get it 🤔

**Comment by busykoala** [comment]
Yes I did, sorry. https://github.com/4teamwork/ftw.testing#generic-setup-uninstall-test

**Comment by jone** [comment]
Now it makes sense 😉 

So: +1, feel free to make a pull request 😉
